### ISSUE TITLE
no install script

### ISSUE THREAD

**Issue by dwiel** [ToxicFrog/vstruct#26]
I know a copy into a particular directory is all that is needed, but it would be nice to take this one more step to a more standard process.  Do you have thoughts on how to take this forward?  I see LuaDist has a copy of the repo, but it is out of date.  What about a luarock?  I'd be willing to help take it in whichever direction it should go.

**Comment by ToxicFrog** [comment]
The LuaDist and LuaForWindows copies of vstruct are handled by those projects' maintainers, so if they're out of date they're the ones who need to be poked.

As for adding an install script to vstruct itself -- I've never used LuaRocks or written a rockspec, but I wouldn't expect it to be difficult for a project this simple. Is it something I could include in vstruct, or would I have to submit it to a luarocks repo somewhere?

Apart from that, the first thing that comes to mind is just writing a simple install.sh that looks at package.path and chooses an install location based on that.

**Comment by deepakjois** [comment]
Please see #27  and let me know your thoughts.

**Comment by ToxicFrog** [comment]
I think we can safely close this since it's been packaged for luarocks, and people who don't use luarocks are presumably comfortable installing it by hand with `cp`.
