### ISSUE TITLE
Rockspec claims Lua 5.3 compatibility

### ISSUE THREAD

**Issue by drauschenbach** [ToxicFrog/vstruct#32]
The next rockspec should claim `lua >= 5.1, < 5.3` to correctly indicate that vstruct is not yet Lua 5.3 compatible.

**Comment by ToxicFrog** [comment]
I think this is now fixed, but as I don't use luarocks I can't confirm.

**Comment by deepakjois** [comment]
I think I missed this issue earlier.

The change should happen in a separate rockspec file with the version number bumped. I will try and get in a PR do a new Luarocks release for this tomorrow.

**Comment by deepakjois** [comment]
New LuaRocks module has been uploaded: https://luarocks.org/modules/deepakjois/vstruct

Pull request for changes: #33
