### ISSUE TITLE
[feature] Support Lua 5.3

### ISSUE THREAD

**Issue by drauschenbach** [ToxicFrog/vstruct#34]
Just to get this feature on the books. Lua 5.3.2 is the default VM shipped with Fedora nowadays.

**Comment by ToxicFrog** [comment]
Added in 064b602385fdbadb469b79d81160e2987b4b8225

**Comment by drauschenbach** [comment]
The last rockspec said vstruct doesn’t support Lua < 5.3. That needs to be fixed in a new release before it will begin to install correctly.

**Comment by deepakjois** [comment]
I will work on uploading a new release to LuaRocks, but until then the latest source code from master branch should support Lua 5.3, as I understand it.

**Comment by drauschenbach** [comment]
“As you understand it”? I remember trying it once and failing. I recall filing a bug in one of the projects that depends on this lib, because it misrepresented 5.3 support when it was in fact untested.

**Comment by deepakjois** [comment]
@drauschenbach  I am not sure what you are implying. Anyway, the last rockspec, i.e. the one for v2.0.2 correctly indicates that it wont work with Lua 5.3.

```lua
dependencies = {
  "lua >= 5.1, < 5.3"
}
```

Unfortunately it was not tagged properly in the repo so it could not be installed under some cases. That should be fixed now.

A fix for Lua 5.3 was made just a few hours ago. I am pretty sure it works, but I haven't had a chance to use it personally. I will upload a new LuaRocks release whenever I find the time to do that.

**Comment by ToxicFrog** [comment]
As of this morning, master (064b602385fdbadb469b79d81160e2987b4b8225 aka v2.1.0) passes all the test suites on 5.3, provided it was built with `LUA_COMPAT_MATHLIB` (and still works on 5.1 and luajit). The rockspec for 2.1.0-1 is not correct (it claims ≥5.3, when I don't want to commit to 5.4 support without testing it and it still works on 5.1) but its advertisement of 5.3 is.

I should be pushing another version this evening which works even in the absence of `LUA_COMPAT_MATHLIB`, at which point I'll also be fixing the rockspec version bounds.

> “As you understand it”? I remember trying it once and failing. I recall filing a bug in one of the projects that depends on this lib, because it misrepresented 5.3 support when it was in fact untested.

There was a period of about two weeks in 2015, after the release of Lua 5.3, when the README just said "does not support Lua versions prior to 5.1", before it was updated to say "doesn't support versions before 5.1, untested on 5.3 but probably doesn't work".

The rockspecs may have been broken at other times; I don't use luarocks.

**Comment by ToxicFrog** [comment]
924d3dd63043189e4a7ef6b1b54b19208054cc0f releases version 2.1.1; it now has a pure-lua implementation of `frexp()`, testing for it, and corrected version bounds for the rockspecs.
