### ISSUE TITLE
Release 2.1.1 on luarocks

### ISSUE THREAD

**Issue by ToxicFrog** [ToxicFrog/vstruct#40]
@deepakjois I have never used luarocks -- will it pick up the new rockspecs automatically or does something need to be done?

**Comment by deepakjois** [comment]
The rockspecs do not get picked up automatically. Somebody needs to do a `luarocks upload` to the public luarocks repository.

I havent had the time to do it and I am sorry about it. I continue to be busy with other things and cannot commit to a specific timeline at the moment.  I will try and get around to it in a month or so.

If somebody else wants to upload the luarocks package, I am happy to do whatever needs to be done to relinquish ownership of the package.

**Comment by deepakjois** [comment]
This is done now:
https://luarocks.org/modules/deepakjois/vstruct/2.1.1-1

**Comment by ToxicFrog** [comment]
Thank you!
