### ISSUE TITLE
New versions are blocking Lua 5.4

### ISSUE THREAD

**Issue by alerque** [ToxicFrog/vstruct#41]
Using an old release without the upper version limit seems to work okay (at least for my use case) but trying to use the newest 2 releases of this on Lua 5.4 block because an upper limit was added.

What needs to be done to support Lua 5.4?

**Comment by ToxicFrog** [comment]
Probably not much, if anything; I've looked through the list of incompatibilities introduced in 5.4 and I don't think any of them should affect it. I just haven't had time to build 5.4 and run it through the test suite lately. I'll try to get to it today or this weekend.

**Comment by ToxicFrog** [comment]
I've tested v2.1.1 with 5.4 and it works fine, so I've updated the 2.1.1 rockspec. 2.1.0 also works under the same conditions as 5.3 (you need legacy math functions enabled at compile time, which is the default). I've updated that rockspec as well.

Both rockspecs will still need to be uploaded to luarocks; @deepakjois is the maintainer on the luarocks side.

**Comment by deepakjois** [comment]
Force uploaded both the rockspecs. So they should work with 5.4 now.

**Comment by ToxicFrog** [comment]
Thank you!
